PushAMP/pamagent

pamagent/trace.py
pamagent/web_transaction.py

Refactor Tracers

---

pamagent/agent.py
pamagent/hooks/django_hook.py
pamagent/hooks/requests_hook.py
pamagent/tests/test_wrappers.py
pamagent/trace.py
pamagent/wrapper.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pushamp/pamagent/4)

Pamp 3 (Add init monkey patching)

---

.travis.yml
MANIFEST.in
README.MD
pamagent/tests/urls.py
pamagent/trace.py
pamagent/transaction.py
rust_setuptools.py
setup.cfg
setup.py
tox.ini

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pushamp/pamagent/5)

Pamp 4 Travis and pytest

---

pamagent/trace.py
pamagent/transaction.py
pamagent/web_transaction.py
pamcore/src/core.rs
pamcore/src/lib.rs

#PAMP-6 Stage Review
The name of the module does not make sense. The module name can be taken from func_name
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pushamp/pamagent/6)

PAMP-6 Add function_name to trace

---

pamcore/src/core.rs
pamcore/src/lib.rs

#PAMP-7 Stage Review
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pushamp/pamagent/7)

PAMP-7 Refactor

---

pamagent/hooks/requests_hook.py
pamagent/tests/test_wrappers.py
pamagent/trace.py
pamcore/src/core.rs
pamcore/src/lib.rs

#PAMP-8 Stage Review
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pushamp/pamagent/8)

Add http method to profile stat

---

pamagent/trace.py
pamagent/transaction.py
pamagent/web_transaction.py
pamagent/wrapper.py
rust_setuptools.py

#PAMP-12 Stage Review
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pushamp/pamagent/9)

All Codacy issue will resolved

---

pamagent/tests/test_wrappers.py
pamagent/transaction.py
pamcore/src/core.rs
pamcore/src/lib.rs

#PAMP-11 Stage Review
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pushamp/pamagent/10)

Resolve issue

---

pamcore/src/core.rs
pamcore/src/output.rs

#PAMP-19 Stage Review
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pushamp/pamagent/15)

Add delay for output loop

---

pamagent/agent.py
pamagent/hooks/_dbapi2.py
pamagent/hooks/sqlite_hook.py
pamagent/tests/test_wrappers.py
pamagent/trace.py
pamagent/utils/sql_statement.py
pamagent/web_transaction.py
pamagent/wrapper.py
pamcore/src/core.rs
pamcore/src/lib.rs
tox.ini

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pushamp/pamagent/17)

Add SQLIte hook

---

README.MD

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pushamp/pamagent/18)

Add a Codacy badge to README.MD

---

.travis.yml
pamcore/Cargo.toml
pamcore/src/core.rs
pamcore/src/lib.rs
pamcore/src/output.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pushamp/pamagent/19)

#PAMP-21 Implement auto reconnnect

---

.travis.yml
pamagent/agent.py
pamagent/hooks/dbapi2.py
pamagent/hooks/psycopg2_hook.py
pamagent/hooks/sqlite_hook.py
pamagent/tests/test_wrappers.py
pamagent/trace.py
pamagent/wrapper.py
pamcore/src/core.rs
pamcore/src/output.rs
setup.py
tox.ini

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pushamp/pamagent/20)

#Pamp 26 Add PostgreSQL support

---

.travis.yml
pamagent/agent.py
pamagent/hooks/mysql_hook.py
pamagent/tests/test_wrappers.py
pamagent/utils/sql_statement.py
pamcore/src/core.rs
tox.ini

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pushamp/pamagent/21)

#Pamp 27 Add support mysql-connector

---

pamagent/hooks/psycopg2_hook.py
pamagent/tests/hooks/test_psycopg2_hook.py
pamcore/src/lib.rs
setup.py

Remove urllib3 dependecy
Add build_wheel script
#PAMP-34 Stage Review
Resolve issue
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pushamp/pamagent/22)

Prepare to multilinux

---

pamagent/trace.py
pamcore/Cargo.toml
pamcore/src/core.rs
pamcore/src/lib.rs
pamcore/src/output.rs

#PAMP-30 Stage Review
Resolve issue
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pushamp/pamagent/23)

Add exponential backoff and retry to initial connect and reconnect

---

pamagent/agent.py
pamcore/Cargo.toml
pamcore/src/lib.rs
pamcore/src/logging.rs
pamcore/src/output.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pushamp/pamagent/24)

Add logging

---

.travis.yml
README.MD
pamagent/hooks/mysql_hook.py
pamagent/tests/test_wrappers.py
tox.ini

#PAMP-33 Stage Review
Resolve issue
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pushamp/pamagent/25)

Add support mysql-connector-python

---

.pyup.yml
MANIFEST.in
requirements.txt
setup.py

#PAMP-38 Stage Review
Resolve issue
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pushamp/pamagent/28)

Integrate to pyup

---

.travis.yml
build-wheels.sh
pamagent/tests/test_wrappers.py
pamcore/Cargo.toml
pamcore/src/output.rs
requirements.txt
setup.py

#PAMP-41 Stage Review
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pushamp/pamagent/32)

PAMP-41 Add line separator

---

.travis.yml
README.MD
pamagent/agent.py
pamagent/hooks/redis_hook.py
pamagent/tests/test_wrappers.py
pamagent/trace.py
pamcore/src/core.rs
pamcore/src/lib.rs
tox.ini

PAMP-40 Add redis-py support
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pushamp/pamagent/34)

PAMP-40 Add redis-py support

---

pamagent/hooks/dbapi2.py
pamagent/hooks/mysql_hook.py
pamagent/hooks/psycopg2_hook.py
pamagent/hooks/sqlite_hook.py
pamagent/trace.py
pamcore/src/core.rs
pamcore/src/lib.rs
pamcore/src/output.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pushamp/pamagent/35)

#PAMP-45 Refacor

---

pamagent/agent.py
pamagent/hooks/dbapi2.py
pamagent/hooks/django_hook.py
pamagent/hooks/mysql_hook.py
pamagent/hooks/redis_hook.py
pamagent/hooks/requests_hook.py
pamagent/hooks/sqlite_hook.py
pamagent/tests/test_wrappers.py
pamagent/tests/urls.py
pamagent/trace.py
pamagent/transaction.py
pamagent/transaction_cache.py
pamagent/web_transaction.py
pamagent/wrapper.py

#PAMP-43 Stage Review
Resolve issue
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pushamp/pamagent/36)

#PAMP-43 Fix transation_path in django

---

.travis.yml
pamagent/tests/test_wrappers.py
pamagent/web_transaction.py
pamcore/src/logging.rs
tox.ini

#PAMP-47 End Trace when wsgi response done
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pushamp/pamagent/38)

End Trace when wsgi response done
